repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest revision
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: debug-statements
    -   id: check-docstring-first


-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3

# -   repo: https://github.com/pycqa/flake8
#     rev: 4.0.1
#     hooks:
#     -   id: flake8

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.931
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-requests]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn